### ISSUE TITLE
Not working in Fabric for me

### ISSUE THREAD

**Issue by Daymond2253** [joshuaepstein/advancementtrophies#1]
Hello, I play with this mod in survival with others mods and when I complete advancement I don't get trophies.
I have tried “monster hunter”,” Stone Age",” Hot Stuff” & “Ice Bucket Challenge”.
Fabric.

**Comment by joshuaepstein** [comment]
Fabric mod is having some issues currently. I have "unpublished" the mod and I will continue to work on the issue

**Comment by Daymond2253** [comment]
Ok, I will wait, bro! Please don't discontinue it!
