### ISSUE TITLE
Localization of items

### ISSUE THREAD

**Issue by CCCClear** [joshuaepstein/advancementtrophies#10]
Currently in the latest version of 1.18.2 Forge, all trophy blocks are localized, but trophy items and their tooltips are still not localized, can you add fields to the lang file for them?

**Comment by joshuaepstein** [comment]
What language are you using, I have done a en_us language file but that is it

**Comment by CCCClear** [comment]
![2022-08-29_01 06 57](https://user-images.githubusercontent.com/44665051/187086133-59e5bc5e-3497-4c58-a124-93fd12b8af7c.png)
Here's how it works in the game

**Comment by joshuaepstein** [comment]
Ah, Ok, I will work on getting that fixed for you, Should be fixed in the next update.

**Comment by joshuaepstein** [comment]
Would you be willing to translate the words Trophy and Advancement to that language so that I can add it to the mod

**Comment by CCCClear** [comment]
Thank you so much for getting started on such a small problem.

**Comment by joshuaepstein** [comment]
I have fixed this issue and is ready in the next version, unfortunately I am trying to fix a rendering issue (FPS loss with trophies) so this will be out when that is fixed.

**Comment by CCCClear** [comment]
Maybe you can release a hot fix update first？
I think FPS issues will take you quite a while to fix.
