### ISSUE TITLE
Crash upon starting new world

### ISSUE THREAD

**Issue by D-Bigboy-302** [joshuaepstein/advancementtrophies#2]
Forge: 40.1.54
Mod: 1.1

Most likely a mod conflict. 

Crash log:
[crash-2022-07-13_13.31.49-server.txt](https://github.com/joshuaepstein/advancementtrophies/files/9105901/crash-2022-07-13_13.31.49-server.txt)

**Comment by joshuaepstein** [comment]
Will be fixed in the next patch. Just need to build it and send it for review.

**Comment by joshuaepstein** [comment]
Issue has been fixed in version 1.3 (Been sent for approval at curseforge)
