### ISSUE TITLE
Trophy sometimes vanishes

### ISSUE THREAD

**Issue by Sheep7798** [joshuaepstein/advancementtrophies#3]
I'm on the latest fabric version.

When I place a trophy, whatever the advancement is, it disappears : it's placed for like half a second, then it's gone.
After experimenting, I was able to find that if I use creative mode to duplicate the trophy in my inventory, it won't disappear after placing it down.

To reproduce it, try with the sculk catalyst advancement : place a scull catalyst, then kill a mob near it : you will get a trophy in your inventory. Then,  you have 2 options : 
- place the trophy and it will disappear
- duplicate the trophy before placing it down : the trophy won't disappear

**Comment by joshuaepstein** [comment]
Aware of this bug, I have removed the mod version from all download sites and I am looking into fixing this issue. New version should be out soon.
