### ISSUE TITLE
FPS lost after placing trophies

### ISSUE THREAD

**Issue by BrizoDood** [joshuaepstein/advancementtrophies#8]
Any trophy is earned, intended to place it, and I lose major FPS.

**Comment by joshuaepstein** [comment]
Hi, I am sorry that you are experiencing this, I will look more into this and get back to you. I will be, hopefully, releasing a new update in the next week or two so it will most likely come out with that update.

**Comment by DeadlyAccurate** [comment]
I'm having this issue, too. Forge 40.1.74 (MC 1.18.2)
advancementtrophies-1.4-forge-1.18.2.jar

**Comment by joshuaepstein** [comment]
I am aware of this issue, After testing with other rendering methods, I cannot find a solution, I will continue to find fixes for this, I will keep you up to date

**Comment by joshuaepstein** [comment]
In developement, I have now fixed this issue, it will be shipped within the next week

**Comment by joshuaepstein** [comment]
This has been fixed and released for 1.19.2 Forge - https://www.curseforge.com/minecraft/mc-mods/advancement-trophies/files/4278730
